to_do_list/planner/urls.py
from django.conf.urls import url

from . import views

app_name = 'planner'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<day_date>[0-9]{4}-[0-9]{2}-[0-9]{2})$', views.DayView.as_view(), name='day_view'),
    url(r'^(?P<day_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<pk>[0-9]+)/$', views.EventDetailView.as_view(),
        name='event_details'),
    url(r'day_new/$', views.day_new, name='day_new'),
    url(r'^(?P<day_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/event_new/$', views.event_new, name='event_new'),
    url(r'^(?P<day_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/event_edit#id=(?P<id>[0-9]+)/$', views.event_edit,
        name='event_edit'),
    url(r'^(?P<day_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/event_delete#id=(?P<id>[0-9]+)/$', views.event_delete,
        name='event_delete'),
    url(r'^(?P<day_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/day_delete/$', views.day_delete,
        name='day_delete'),
]

to_do_list/to_do_list/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^planner/', include('planner.urls')),
    url(r'^', include('planner.urls'))
]

to_do_list/planner/models.py
from datetime import time
from django.db import models


class Day(models.Model):
    date = models.DateField('day\'s happening time', unique=True)

    def __str__(self):
        return self.date.strftime("%A %d. %B %Y")


class Event(models.Model):
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    title = models.CharField(default="empty event title", max_length=64)
    description = models.TextField(default="empty description.")
    start_time = models.TimeField(default=time.min)
    end_time = models.TimeField(default=time.max)

    def __str__(self):
        return str(self.title) + " (" + str(self.start_time) + " - " + str(self.end_time) + ")"

to_do_list/planner/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Day, Event


class DayForm(forms.ModelForm):
    error_css_class = 'alert alert-danger'

    class Meta:
        model = Day
        fields = ('date',)

    def __init__(self, *args, **kwargs):
        super(DayForm, self).__init__(*args, **kwargs)
        self.fields['date'].label = 'Select a date:'


class EventForm(forms.ModelForm):
    #errorlist_css_class = 'alert alert-danger'

    class Meta:
        model = Event
        fields = ('title', 'start_time', 'end_time', 'description',)

    def clean(self):
        cleaned_data = super(EventForm, self).clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")

        if start_time > end_time:
            raise ValidationError('Start time cannot be later than end time.')
        return cleaned_data

to_do_list/planner/views.py
from django.core.exceptions import ValidationError
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from .models import Day, Event
from .forms import DayForm, EventForm


class IndexView(generic.ListView):
    template_name = 'planner/index.html'
    context_object_name = 'planned_days_list'

    def get_queryset(self):
        return Day.objects.all().order_by('date')


class DayView(generic.ListView):
    model = Event
    context_object_name = 'events_of_the_chosen_day_list'

    def get_context_data(self, **kwargs):
        context = super(DayView, self).get_context_data()
        context['day_date'] = self.kwargs['day_date']
        return context

    def get_queryset(self):
        return Day.objects.get(date=self.kwargs['day_date']).event_set.all().order_by('start_time')


class EventDetailView(generic.DetailView):
    model = Event
    template_name = 'planner/event_detail.html'
    context_object_name = 'current_event'


def day_new(request):
    if request.method == 'POST':
        form = DayForm(request.POST)
        if form.is_valid():
            entered_day = form.save()
            return redirect('/planner/' + str(entered_day.date))
    else:
        form = DayForm(initial={'date': 'yyyy-mm-dd'})
    return render(request, 'planner/day_new.html', {'form': form})


def event_new(request, **kwargs):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            new_event = form.save(commit=False)
            new_event.day = Day.objects.get(date=kwargs['day_date'])
            new_event.save()
            return redirect('/planner/' + str(new_event.day.date) + "/" + str(new_event.id))
    else:
        form = EventForm()
    return render(request, 'planner/event_new.html', {'form': form, 'day_date': kwargs['day_date']})


def event_edit(request, id=None, **kwargs):
    if id:
        event = get_object_or_404(Event, pk=id)
    else:
        event = Event()

    form = EventForm(request.POST, instance=event, )
    if request.method == 'POST':
        try:
            if form.is_valid():
                new_event = form.save(commit=False)
                new_event.day = Day.objects.get(date=kwargs['day_date'])
                new_event.save()
                return redirect('/planner/' + str(new_event.day.date) + "/" + str(new_event.id))
        except TypeError:
            pass
    else:
        form = EventForm(instance=event)
    return render(request, 'planner/event_new.html', {'form': form, 'day_date': kwargs['day_date']})


def event_delete(request, **kwargs):
    event = get_object_or_404(Event, pk=kwargs['id'])
    if event:
        event.delete()
    return redirect('planner:day_view', day_date=kwargs['day_date'])


def day_delete(request, **kwargs):
    day = get_object_or_404(Day, date=kwargs['day_date'])
    if day:
        day.delete()
    return redirect('planner:index')

to_do_list/planner/templates/planner/day_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New day form</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'planner/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
</head>
<body>
<div class="main-cont">
    {% block content %}
        <h2>Plan a new day</h2>
        <form method="POST" class="post-form">
            <div class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <button type="submit" class="save btn btn-success">Plan this day</button>
            <a href={% url 'planner:index' %} role="button" class="save btn btn-default">Go back to the main
                page</a>
        </form>
    {% endblock %}
</div>
</body>
</html>

to_do_list/planner/templates/planner/event_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New day</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'planner/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
</head>
<body>
<div class="main-cont">

    <p>
        <h2>{{ current_event }}</h2>
        <h3>{{ current_event.description }}</h3>
    </p>
    <a href="{% url 'planner:event_edit' current_event.day.date current_event.id %}">
        <button type="button" class="save btn btn-primary">Edit</button>
    </a>
    <a href="{% url 'planner:event_delete' current_event.day.date current_event.id %}">
        <button type="button" class="save btn btn-danger">Delete</button>
    </a>
    <a href="{% url 'planner:day_view' current_event.day.date %}">
        <button type="button" class="save btn btn-default">Go back</button>
    </a>
</div>
</body>
</html>

to_do_list/planner/templates/planner/event_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Day {{ day_date }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'planner/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
</head>
<body>
<div class="main-cont">
    {% block content %}
        <h2>Events</h2>
        {% if not events_of_the_chosen_day_list %} <p>There are no events planned for this day.</p> {% endif %}
        <ul>
            {% for event in events_of_the_chosen_day_list %}
                <li><a href="{% url 'planner:event_details' event.day.date event.id %}">{{ event }}</a></li>
            {% endfor %}
        </ul>

        <a href={% url 'planner:event_new' day_date %}>
            <button type="button" class="save btn btn-success"> Add a new event</button>
        </a>
        <a href={% url 'planner:day_delete' day_date %}>
            <button type="button" class="save btn btn-danger"> Delete the whole day</button>
        </a>
        <a href={% url 'planner:index' %}>
            <button type="button" class="save btn btn-default"> Go back to the main page</button>
        </a>
    {% endblock %}
</div>
</body>
</html>

to_do_list/planner/templates/planner/event_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New event form</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'planner/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>

</head>
<body>
<div class="main-cont">
    {% block content %}
        <p>Enter details concerning the event in the form below:</p>
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-success">Submit the event</button>
            <a href="{% url 'planner:day_view' day_date %}">
                <button type="button" class="save btn btn-default">Go back</button>
            </a>

        </form>

    {% endblock %}
</div>
</body>
</html>

to_do_list/planner/templates/planner/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index | Planner</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'planner/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
</head>
<body>
<div class="main-cont">
    <a href={% url 'planner:day_new' %}>
        <button type="button" class="save btn btn-primary ">Plan a new day</button>
    </a>
    {% if planned_days_list %}
        <ul>
            {% for day in planned_days_list %}
                <li><a href="{% url 'planner:day_view' day.date %}">{{ day }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No days planned yet.</p>
    {% endif %}

</div>
</body>
</html>